### ISSUE TITLE
Add .lib to release

### ISSUE THREAD

**Issue by LemonHX** [mengmo/QuickJS-Windows-Build#7]
it is useful to have .lib file in the release

**Comment by mengmo** [comment]
Since QuickJS does not officially support MSVC at present and I don't use MSVC, I'm not able to add **.lib** files in releases.

But there are some examples to **generate lib from dll**, these may help:
https://web.archive.org/web/20200804202518/http://www.mingw.org/wiki/MSVC_and_MinGW_DLLs
https://wiki.videolan.org/GenerateLibFromDll

**Comment by LemonHX** [comment]
So I forked one and done with MSVC.
